--MI PRIMER BLOQUE PL SQL HOLA MUNDO
--MODO DE DEPURACION
SET SERVEROUTPUT ON;

BEGIN
--AQUI VA LA LOGICA
DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;
/

--SEGUNDO BLOQUE PL SQL USANDO DECLARACION DE VARIABLES
DECLARE
EDAD INTEGER;
NOMBRE VARCHAR2(40);
DIAS INTEGER;

BEGIN
--ASIGNAMOS ESAS VARIABLES
EDAD:=46;
--SACAMOS TU EDAD EN DIAS
DIAS:=EDAD*365;
NOMBRE:='JUAN CARLOS';
DBMS_OUTPUT.PUT_LINE('BUENOS DIAS '||NOMBRE||' TU EDAD EN DIAS '||DIAS);
END;
/

--PASO 1
CREATE TABLE CHICOS (ID INTEGER PRIMARY KEY, VALOR INTEGER);
--PASO 2
CREATE TABLE GRANDES(ID INTEGER PRIMARY KEY, VALOR INTEGER);



DECLARE
EDAD INTEGER;
BEGIN
--ASIGNAMOS UNA EDAD
EDAD:=10;
IF EDAD >18 THEN
INSERT INTO GRANDES VALUES(2,EDAD);
ELSE
INSERT INTO CHICOS VALUES(2,EDAD);
END IF;
END;
/

--LO PROBAMOS
SELECT * FROM GRANDES;
SELECT * FROM CHICOS;








