
--ejercicio de un cursor de tipo implicito
--LO usaremos con la tabla pelicula
SET SERVEROUTPUT ON;

DECLARE
VALOR VARCHAR2(50);
BEGIN
 SELECT TITULO INTO VALOR FROM PELICULA WHERE ID_PELICULA=1; 
 DBMS_OUTPUT.PUT_LINE('EL TITULO DE LA PELICULA ES '||VALOR);
END;
/

-- AHORA VEREMOS UN CURSOR EXPLICITO CON LA MISMA TABLA Y EL
--EJEMPLO MUY PARECIDO

DECLARE
CURSOR CUR_1 IS SELECT * FROM PELICULA;
BEGIN
  FOR REC IN CUR_1 LOOP
   DBMS_OUTPUT.PUT_LINE(' LA PELICULA ES '||REC.TITULO);
   END LOOP;
END;
/

--CURSORES DE REFERENCIA
CREATE OR REPLACE PROCEDURE BUSCAR_PELICULAS(CUR OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CUR  FOR
SELECT * FROM PELICULA;
END;
/

