--a) CREAR KLA TABLA

CREATE TABLE CARTERA_CLIENTES(ID_CLIENTE INTEGER PRIMARY KEY,
    NOMBRE VARCHAR2(40), SUELDO_BASE FLOAT);
    
    --b) GENERAMOS LA SECUENCIA QUE CONTROLARA LA PK
   CREATE SEQUENCE SEC_CARTERA_CLIENTES
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;
   