CREATE TABLE TABLITA_1(ID INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(50), EDAD INTEGER);

--VAMOS A GENERAR NUESTRO  TRIGGER

CREATE OR REPLACE TRIGGER DISP_TABLITA1 BEFORE INSERT ON TABLITA_1 FOR EACH ROW
BEGIN
IF :NEW.EDAD <18 THEN
RAISE_APPLICATION_ERROR(-20001, 'LO SIENTO ERES MENOR DE EDAD!!');
END IF;
END;
/

INSERT INTO TABLITA_1 VALUES(1,'JUAN',23);
SELECT * FROM TABLITA_1;
INSERT INTO TABLITA_1 VALUES(2,'ANA',16);

CREATE OR REPLACE TRIGGER DISP_TODOS AFTER INSERT ON TODOS FOR EACH ROW
BEGIN
IF :NEW.EDAD >18 THEN
INSERT INTO MAYORES VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
ELSE
INSERT INTO MENORES VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
END IF;
END;
/