--CREAMOS LA TABLA ALMACEN
CREATE TABLE ALMACEN(NUMERO_ALMACEN INTEGER,
UBICACION_ALMACEN VARCHAR2(50),
CONSTRAINT PK_NUM_ALMACEN PRIMARY KEY(NUMERO_ALMACEN));

--CREAMOS LA TABLA CLIENTE QUE SE RELACIONA A ALMACEN
CREATE TABLE  CLIENTE(NUMERO_CLIENTE INTEGER,
NUMERO_ALMACEN INTEGER, NOMBRE_CLIENTE VARCHAR2(50),
CONSTRAINT PK_NUM_CLIENTE PRIMARY KEY(NUMERO_CLIENTE),
CONSTRAINT FK1_NUM_ALMACEN FOREIGN KEY(NUMERO_ALMACEN) REFERENCES ALMACEN(NUMERO_ALMACEN));


--PROCEDIMIENTO GUARDAR_ALMACEN
CREATE OR REPLACE PROCEDURE GUARDAR_ALMACEN(MI_ID IN INTEGER, MI_UBI IN VARCHAR2)
AS
BEGIN
INSERT INTO ALMACEN VALUES(MI_ID, MI_UBI);
END;
/

--PROCEDIMIENTO GUARDAR_CLIENTE
CREATE OR REPLACE PROCEDURE GUARDAR_CLIENTE(MI_ID IN INTEGER,
ID_ALMACEN IN INTEGER, NOM_CLIENTE IN VARCHAR2)
AS
BEGIN
INSERT INTO CLIENTE VALUES(MI_ID, ID_ALMACEN, NOM_CLIENTE);
END;
/




