--CREAMOS LA TABLA ALMACEN
CREATE TABLE ALMACEN(NUMERO_ALMACEN INTEGER,
UBICACION_ALMACEN VARCHAR2(50),
CONSTRAINT PK_NUM_ALMACEN PRIMARY KEY(NUMERO_ALMACEN));

--CREAMOS LA TABLA CLIENTE QUE SE RELACIONA A ALMACEN
CREATE TABLE  CLIENTE(NUMERO_CLIENTE INTEGER,
NUMERO_ALMACEN INTEGER, NOMBRE_CLIENTE VARCHAR2(50),
CONSTRAINT PK_NUM_CLIENTE PRIMARY KEY(NUMERO_CLIENTE),
CONSTRAINT FK1_NUM_ALMACEN FOREIGN KEY(NUMERO_ALMACEN) REFERENCES ALMACEN(NUMERO_ALMACEN));


--PROCEDIMIENTO GUARDAR_ALMACEN
CREATE OR REPLACE PROCEDURE GUARDAR_ALMACEN(MI_ID IN INTEGER, MI_UBI IN VARCHAR2)
AS
BEGIN
INSERT INTO ALMACEN VALUES(MI_ID, MI_UBI);
END;
/

--PROCEDIMIENTO GUARDAR_CLIENTE
CREATE OR REPLACE PROCEDURE GUARDAR_CLIENTE(MI_ID IN INTEGER,
ID_ALMACEN IN INTEGER, NOM_CLIENTE IN VARCHAR2)
AS
BEGIN
INSERT INTO CLIENTE VALUES(MI_ID, ID_ALMACEN, NOM_CLIENTE);
END;
/


--TABLA VENDEDOR
CREATE TABLE VENDEDOR(NUMERO_VENDEDOR INTEGER, NOMBRE_VENDEDOR VARCHAR2(60),
                      AREA_VENTAS VARCHAR2(40),
                      CONSTRAINT PK_NV PRIMARY KEY(NUMERO_VENDEDOR)
                      );
                        

--TABLA VENTAS

  CREATE SEQUENCE SEC_VENTAS
      START WITH 1
      INCREMENT BY 1
      NOMAXVALUE;



   --PROCEDIMIENTO VENDEDOR
      CREATE OR REPLACE PROCEDURE GUARDAR_VENDEDOR(MY_NUMERO_VENDEDOR IN INTEGER, MY_NOMBRE_VENDEDOR IN VARCHAR2,MY_AREA_VENTAS IN VARCHAR2)
      AS
      BEGIN
      INSERT INTO VENDEDOR VALUES(MY_NUMERO_VENDEDOR, MY_NOMBRE_VENDEDOR, MY_AREA_VENTAS);
      END;
      /

  CREATE TABLE VENTAS(ID_VENTAS INTEGER, NUMERO_CLIENTE INTEGER, 
      NUMERO_VENDEDOR INTEGER, MONTO_VENTA FLOAT,
      CONSTRAINT PK_IDV PRIMARY KEY(ID_VENTAS),
      CONSTRAINT FK_NC1 FOREIGN KEY(NUMERO_CLIENTE) REFERENCES CLIENTE(NUMERO_CLIENTE),
      CONSTRAINT FK_NV1 FOREIGN KEY(NUMERO_VENDEDOR) REFERENCES VENDEDOR(NUMERO_VENDEDOR)
      );




 --PROCEDIMIENTO VENTAS
      
      CREATE OR REPLACE PROCEDURE GUARDAR_VENTAS(MY_ID OUT INTEGER, MY_NUMERO_CLIENTE IN INTEGER , MY_NUMERO_VENDEDOR IN INTEGER, MY_MONTO_VENTA IN FLOAT)
      AS BEGIN
      SELECT SEC_VENTAS.NEXTVAL INTO MY_ID FROM DUAL;
      INSERT INTO VENTAS VALUES(MY_ID, MY_NUMERO_CLIENTE, MY_NUMERO_VENDEDOR, MY_MONTO_VENTA);
      END;
      /




                                                                          
                                                                          

