CREATE TABLE ALMACEN(NUMERO_ALMACEN INTEGER,
UBICACION_ALMACEN VARCHAR2(40),
CONSTRAINT PK_A_NM PRIMARY KEY (NUMERO_ALMACEN));

CREATE TABLE CLIENTE(NUMERO_CLIENTE INTEGER,
NUMERO_ALMACEN INTEGER, NOMBRE_CLIENTE VARCHAR2(50),
CONSTRAINT PK_C_NC PRIMARY KEY (NUMERO_CLIENTE),
CONSTRAINT FK1_NM FOREIGN KEY(NUMERO_ALMACEN) 
REFERENCES ALMACEN(NUMERO_ALMACEN)   );
--GENERAMOS EL PROCEDIMIENOTO PARA GUARDAR_ALMACEN
CREATE OR REPLACE PROCEDURE GUARDAR_ALMACEN(MY_NM IN INTEGER,
MY_UA IN VARCHAR2) 
AS
BEGIN
INSERT INTO ALMACEN VALUES(MY_NM,MY_UA);
END;
/

CREATE OR REPLACE PROCEDURE GUARDAR_CLIENTE(MY_NC IN INTEGER,
MY_NA IN INTEGER, MY_C IN VARCHAR2)
AS
--VALOR FLOAT;
BEGIN
INSERT INTO CLIENTE VALUES(MY_NC, MY_NA,MY_C);
END;
/

--GUARDAR LOS DATOS DE ALMACEN Y CLIENTE, 
--CON LA INFORMACION DEL EXCEL

BEGIN
GUARDAR_ALMACEN(1,'PLYMUTH');
GUARDAR_ALMACEN(2,'SUPERIOR');
GUARDAR_ALMACEN(3,'BISMARCK');
GUARDAR_ALMACEN(4,'FARGO');
END;
/
SELECT * FROM ALMACEN;

BEGIN
GUARDAR_CLIENTE(18765,4,'DELTA SYSTEMS');
END;
/

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE ALMACEN_CLIENTES
AS
CURSOR CUR_ALMACEN IS SELECT * FROM ALMACEN;
CURSOR CUR_CLIENTE IS SELECT * FROM CLIENTE;
BEGIN

FOR REC_AL IN CUR_ALMACEN LOOP
  FOR REC_CLI IN CUR_CLIENTE LOOP
   DBMS_OUTPUT.PUT_LINE('AQUI DEBE ESTA TU LOGICA');
  END LOOP;
 END LOOP;
END;
/


